title:
  en: My Expenses
  fr: Mes dépenses
  de: Meine Ausgaben
  it: Le mie spese
  es: Mis gastos
  ca: Les Meves Despeses
  tr: Harcamalarım
langs:
  -
    - en
    - English
  -
    - fr
    - Français
  -
    - de
    - Deutsch
  -
    - it
    - Italiano
  -
    - es
    - Español
  -
    - ca
    - Català
  -
    - tr
    - Türkçe
sections:
  summary:
    weight: 1
    url: index.xhtml
    title:
      en: My Expenses
      fr: Mes dépenses
      de: Meine Ausgaben
      it: Le mie spese
      es: Mis gastos
      ca: Les Meves Despeses
      tr: Harcamalarım
    headstuff: |
      <script xmlns="http://www.w3.org/1999/xhtml" src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript" charset="UTF-8"> </script>
      <script xmlns="http://www.w3.org/1999/xhtml" type="text/javascript" src="/script/images.js" charset="UTF-8"> </script>
      <script xmlns="http://www.w3.org/1999/xhtml" type="text/javascript" src="/script/utils.js" charset="UTF-8"> </script>
      <script xmlns="http://www.w3.org/1999/xhtml" src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/jquery-ui.min.js" type="text/javascript" charset="UTF-8"> </script>
      <link xmlns="http://www.w3.org/1999/xhtml" rel="stylesheet" type="text/css" href="/css/screenshots.css" charset="UTF-8"/>
      <link xmlns="http://www.w3.org/1999/xhtml" rel="stylesheet" type="text/css" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/themes/base/jquery-ui.css" charset="UTF-8"/>
  tutorial:
    weight: 2
    url: tutorial_r4/introduction.xhtml
    title: 
      en: "User&#160;guide"
      fr: Manuel
      de: Anleitung
      it: Manuale
      es: Manual
  news:
    weight: 3
    url: news/news4.html
    title:
      en: News
  participate:
    weight: 4
    url: participate.xhtml
    title:
      en: Participate
      de: Mitmachen
      es: Participar
      fr: Participer
      it: Partecipare
    tags:
      - donate
  info:
    weight: 5
    url: info.xhtml
    title:
      en: Information
    tags:
      - credits
  changelog:
    weight: 6
    url: versionlist.xhtml
    title: 
      en: Changelog
      fr: Modifications
      de: Änderungen
      it: Aggiornamenti
      es: Cambios
      ca: Canvis
      tr: Değişiklikler
    styles: |
      dl.versionlist {
        position: relative;
      }
      dl.versionlist dt {
        float: left; clear:left; font-weight: bold; margin-bottom: -1px; margin-right: 2px;
      }
      dl.versionlist dd {
        margin-left: 4.5em;
      }
      .versioncode {
        display: inline-block;
        width: 4.5em;
        }
      .versiondate {
        display: inline-block;
        width: 6em;
      }
  faq:
    weight: 7
    url: faq.xhtml
    title:
      en: FAQ
      fr: FAQ
      de: FAQ
      it: FAQ
      es: FAQ
      tr: SSS
  imprint:
    url: imprint.xhtml
    title:
      en: Imprint
      de: Impressum
      it: Imprinto
    tags:
      - privacy
missing_langs: "Pусский, Português, Slovenčina, Nederlands, Ελληνικά, Čeština, Magyar,  ‏العربية‎, Română, 中文"
versions:
  -
    - 1.7.0a3
    - 2013-04-22
    -
      en: |
        Edit templates.
  -
    - 1.7.0a2
    - 2013-04-19
    -
      en: |
        Licence keys.
  -
    - 1.7.0a1
    - 2013-04-18
    -
      en: |
        Swipe through accounts.
        Access to selected new features now depends on installation of Contrib App.
        Restore backup without install/uninstall.
        Ask for confirmation when restoring upon install.
        Display aggregate financial situation in account list.
        Resolved flickering issue in light theme.
  -
    - 1.6.8
    - 2013-02-23
    -
      ca: |
        Localitzat icona de l'aplicació i el botó de la data.
        Les notes es mostren a la llista de transaccions.
      de: |
        App-Symbol und Datum-Schaltfläche lokalisiert.
        Notizen werden in der Buchungsliste angezeigt.
      en: "Localized app icon and date button. Notes are displayed in transaction list."
      es: |
        El icono de la aplicación y el botón de la fecha estan localizados.
        Los apuntes se muestran en la lista de transacciones.
      fr: |
        L'icône de l'application et le bouton de la date sont localisés.
        Les remarques sont affichées dans la liste des transactions.
      it: |
        Localizzata app icona e il pulsante data.
        Le note sono visualizzate nella lista delle transazioni.
      tr: |
        Uygulama ikonu ve tarih düğmesi tercüme edildi.
        Notlar muamele listesinde görüntüleniyor.
  -
    - 1.6.7
    - 2013-02-08
    -
      ca: |
        Colors diferents per a cada compte.
        Traducció al Turc.
      de: |
        Konfigurierbare Farben für Konten.
        Türkische Übersetzung.
      en: "Configurable colors for accounts. Turkish translation."
      es: |
        Colores configurables para las cuentas.
        Traducción al turco.
      fr: |
        Couleurs configurables pour les comptes.
        Traduction en turc.
      it: |
        Colori configurabili per i conti.
        Traduzione in turco.
      tr: |
        Hesaplar için ayarlanabilir renkler.
        Türkçe tercüme.
  -
    - 1.6.6
    - 2013-01-26
    -
      ca: |
        Associació entre els tipus de comptes i mètodes de pagament reparats.
        Utilitza la mida del tipus de lletra estàndard del sistema.
      de: |
        Problem bei Verknüpfung von Kontotyp und Zahlungsweise behoben.
        Standard-Schriftgröße des Systems verwenden.
      en: |
        Bug fix: Associating account types with payment methods.
        Use system default font size.
      es: |
        Asociación de tipos de cuenta con métodos de pago reparada.
        Utilizar el tamaño de la fuente estándar del sistema.
      fr: |
        Association entre les types de comptes et les méthodes de paiement réparée.
        Utiliser la taille de police par défaut du système.
      it: |
        Associazione tra i tipi di conto e metodi di pagamento riparati.
        Utilizare dimensioni carattere standard di sistema.
      tr: |
        Hata düzeltmesi: Hesap türlerinin ödeme metotları ile ilişkilendirilmesi.
        Varsayılan sistem yazıtipi boyutunu kullan.
  -
    - 1.6.5
    - 2013-01-24
    -
      ca: |
        Aparença: tema fosc.
        Traducció al català.
        Nova suma de transferències a la vista dels comptes.
      de: |
        Dunkler UI Stil.
        Übersetzung ins Katalanische.
        Summe der Umbuchungen in der Kontenübersicht anzeigen.
      en: |
        Dark UI theme.
        Catalan translation.
        Added sum of transfers in account overview.
      es: |
        Tema UI oscuro.
        Traducción catalán.
        Añadido suma de las traslados en resumen de cuentas.
      fr: |
        Style sombre de l'interface utilisateur.
        Traduction en catalan.
        Afficher le total des tansfers dans le sommaire des comptes.
      it: |
        Stile buio.
        Traduzione catalana.
        La soma dei trasferimenti aggiunta al sommario dei conti.
  -
    - 1.6.0
    - 2012-12-24
    -
      ca: |
        Creare operazione riguardo modelli.
        È possibile configurare set di caratteri del file QIF (compatibilità MS Money).
        Miglioramenti dell'interfaccia utente.
        Mostra i recenti operazioni in cima.
        L'elenco degli conti mostra una panoramica della situazione finanziaria.
      de: |
        Buchungen aus Vorlagen erzeugen.
        Zeichensatz des QIF-Exports konfigurierbar zur besseren Unterstützung von MS Money.
        Verbesserungen der Benutzerschnittstelle.
        Neueste Buchungen oben.
        Kontenliste zeigt aktuellen Finanzstatus an.
      en: "Create transactions from templates. Character encoding of exported QIF file configurable to support MS Money. User interface improvements. Newest transactions on top. Account list gives overview of financial status"
      es: |
        Crear asientos a partir de una plantilla.
        Puede configurar codificación de caracteres (compatibilidad con MS Money).
        Mejora de la interfaz de usuario.
        Mostrar más nuevas transacciones en la parte superior.
        La lista de cuentas muestra el estado financiero actual.
      fr: |
        Créer des opérations à partir de modèles.
        Encodage de l'export QIF configurable en vue de compatibilté avec MS Money.
        Améliorations de l'interface usager.
        La liste des opérations est triée avec les plus récentes en haut.
        La liste des comptes affiche un aperçu de la situation financiere.
      it: |
        Creare operazione riguardo modelli.
        È possibile configurare set di caratteri del file QIF (compatibilità MS Money).
        Miglioramenti dell'interfaccia utente.
        Mostra i recenti operazioni in cima.
        L'elenco degli conti mostra una panoramica della situazione finanziaria.
  -
    - 1.5.1
    - 2012-10-21
    -
      en: "Fixed problem with restore from old backups. Show payment method in transaction details."
  -
    - 1.5.0
    - 2012-10-20
    -
      en: "Payment methods. FTP transfer factored out to SendWithFTP app. Bug fixes (Issues #24, #27, #28 ,#29, #30, #32, #33). Improved QIF format (header and category)."
  -
    - 1.4.12
    - 2012-04-26
    -
      en: "User interface translated to Spanish. Move transaction to different account. Parties list sorted alphabetically."
  -
    - 1.4.11
    - 2012-04-20
    -
      en: "Improved stability of categories import and ftp transfer. Added FAQ. Generic export through any installed file transfer app."
  -
    - 1.4.10
    - 2012-04-14
    -
      en: "Improved usability and added configurability to input of currency amounts."
  -
    - 1.4.9.1
    - 2012-04-07
    -
      en: "Solved crash when importing categories in Italian locale and two minor problems with account deletion."
  -
    - 1.4.9
    - 2012-03-31
    -
      en: "Additional features for list of payers/payees (import from Grisbi, delete). Fixed display of buttons in ICS."
  -
    - 1.4.8
    - 2012-03-26
    -
      en: "Revamped user interface. Some bug-fixes."
  -
    - 1.4.7.2
    - 2012-03-13
    -
      en: "Italian categories and tutorial. Added menu icons."
  -
    - 1.4.7.1
    - 2012-03-10
    -
      en: "Fixed layout of expense list in landscape mode. Bug fix for backup."
  -
    - 1.4.7
    - 2012-03-09
    -
      en: "Improved usability of currency input. Reduced apk size, since tutorial is no longer included, but hosted on Github."
  -
    - 1.4.6
    - 2012-03-04
    -
      en: "Backup and restore of database and preferences. User interface translated to Italian."
  -
    - 1.4.5.2
    - 2012-02-27
    -
      en: "Tutorial translated to German and French. Fixed problems with orientation change during categories import and help and changelog dialog. Support for Grisbi file format 0.5.0."
  -
    - 1.4.5.1
    - 2012-02-17
    -
      en: "Problem with export (FTP, email) fixed."
  -
    - 1.4.5
    - 2012-02-13
    -
      en: "Support for sending QIF file via email. Reduced memory footprint."
  -
    - 1.4.4
    - 2012-02-08
    -
      en: "FTP upload done in background. Default account created in user's language and currency."
  -
    - 1.4.3
    - 2012-02-03
    -
      en: "Improved parsing of number input in German locale. Upload of QIF file to FTP server."
  -
    - 1.4.1
    - 2012-01-31
    -
      en: "Input of transaction amounts now respects user's locale. Bug fix: Opening balance could not be set."
  -
    - 1.4.0
    - 2012-01-27
    -
      en: "Currencies now handled with java.util.Currency. Support for transfers between accounts."
  -
    - 1.3.2
    - 2012-01-17
    -
      en: "Improved help and included tutorial."
  -
    - 1.3.0
    - 2012-01-13
    -
      en: "Cleaned up UI."
  -
    - 1.2.8
    - 2012-01-08
    -
      en: "Fixed bug in export."
  -
    - 1.2.7
    - 2012-01-07
    -
      en: "Added payee field. Ignore empty fields in QIF export."
  -
    - 1.2.6
    - 2011-11-06
    -
      en: "Better management of categories: Default category files from Grisbi are now included in the app, categories can be deleted and renamed."
  -
    - 1.2.0
    - 2011-10-07
    -
      en: "Support for multiple accounts. No upgrade. You have to uninstall older versions."
  -
    - 1.1.3
    - 2011-06-06
    -
      en: "Use workaround class for bug in SimpleCursorTreeAdapter (NullPointerException when adding the first subcategory) from http://code.google.com/p/android/issues/detail?id=9170; better feedback when category import goes wrong."
  -
    - 1.1.2
    - 2011-05-18
    -
      en: "Sort categories by usages; Allow assignment of main category; Allow manual creation of categories; Improved handling of categories import."

