title:
  en: My Expenses
  fr: Mes dépenses
  de: Meine Ausgaben
  it: Le mie spese
  es: Mis gastos
langs:
  en: English
  fr: Français
  de: Deutsch
  it: Italiano
  es: Español
sections:
  summary:
    url: index.html
    title:
      en: Summary
      fr: Sommaire
      de: Zusammenfassung
      it: Riassunto
      es: Resumen
  tutorial:
    url: tutorial_r4/introduction.html
    title: 
      en: User guide
      fr: Manuel
      de: Anleitung
      it: Manuale
      es: Manual
  news:
    url: news/news2.html
    title:
      en: News
  install:
    url: install.html
    title: 
      en: Install
  donate:
    url: donate.html
    title:
      en: Donate
  screenshots:
    url: screenshots.html
    title:
      en: Screenshots
  privacy:
    url: privacy.html
    title:
      en: "Privacy&#160;policy"
  changelog:
    url: versionlist.html
    title: 
      en: Changelog
  credits:
    url: credits.html
    title:
      en: Credits
  licence:
    url: licence.html
    title:
      en: Licence
  sourcecode:
    url: sourcecode.html
    title:
      en: Sourcecode
  links:
    url: links.html
    title:
      en: Links
  plans:
    url: plans.html
    title:
      en: "Future&#160;plans"

