title:
      en: My Expenses
      fr: Mes dépenses
      de: Meine Ausgaben
      it: Le mie spese
      es: Mis gastos
langs:
  en: English
  fr: Français
  de: Deutsch
  it: Italiano
  es: Español
sections:
  - 
    id: summary
    url: index.html
    title:
      en: Summary
      fr: Sommaire
      de: Zusammenfassung
      it: Riassunto
      es: Resumen
    langs:
      - en
      - fr
      - de
      - it
      - es
  - 
    id: tutorial
    url: tutorial_r4/introduction.html
    title: 
      en: User guide
      fr: Manuel
      de: Anleitung
      it: Manuale
      es: Manual
    langs: 
      - en
      - fr
      - de
      - it
      - es
  -
    id: news
    url: news/news2.html
    title:
      en: News
  -
    id: install
    url: install.html
    title: 
      en: Install
  -
    id: donate
    url: donate.html
    title:
      en: Donate
  -
    id: screenshots
    url: screenshots.html
    title:
      en: Screenshots
  -
    id: privacy
    url: privacy.html
    title:
      en: Privacy policy
  -
    id: changelog
    url: versionlist.html
    title: 
      en: Changelog
  -
    id: credits
    url: credits.html
    title:
      en: Credits
  -
    id: sourcecode
    url: sourcecode.html
    title:
      en: Sourcecode
  -
    id: links
    url: links.html
    title:
      en: Links
  -
    id: plans
    url: plans.html
    title:
      en: Future plans

