title:
  en: My Expenses
  fr: Mes dépenses
  de: Meine Ausgaben
  it: Le mie spese
  es: Mis gastos
langs:
  -
    - en
    - English
  -
    - fr
    - Français
  -
    - de
    - Deutsch
  -
    - it
    - Italiano
  -
    - es
    - Español
sections:
  summary:
    weight: 1
    url: index.xhtml
    title:
      en: Summary
      fr: Sommaire
      de: Zusammenfassung
      it: Riassunto
      es: Resumen
  tutorial:
    weight: 2
    url: tutorial_r4/introduction.xhtml
    title: 
      en: "User&#160;guide"
      fr: Manuel
      de: Anleitung
      it: Manuale
      es: Manual
  news:
    weight: 3
    url: news/news2.html
    title:
      en: News
  install:
    weight: 4
    url: install.xhtml
    title: 
      en: Install
  donate:
    weight: 5
    url: donate.xhtml
    title:
      en: Donate
  screenshots:
    weight: 6
    url: screenshots.xhtml
    title:
      en: Screenshots
  privacy:
    weight: 7
    url: privacy.xhtml
    title:
      en: "Privacy&#160;policy"
  changelog:
    weight: 8
    url: versionlist.xhtml
    title: 
      en: Changelog
  credits:
    weight: 9
    url: credits.xhtml
    title:
      en: Credits
  licence:
    weight: 10
    url: licence.xhtml
    title:
      en: Licence
  sourcecode:
    weight: 11
    url: sourcecode.xhtml
    title:
      en: Sourcecode
  links:
    weight: 12
    url: links.xhtml
    title:
      en: Links
  plans:
    weight: 13
    url: plans.xhtml
    title:
      en: "Future&#160;plans"

