navig:
  -
    url: /index.html
    title: Summary
  -
    url: /en/tutorial_r4/introduction.html
    title: User guide
    section: manual
  -
    url: /news/news2.html
    title: News
    section: news
  -
    url: /install.html
    title: Install
  -
    url: /donate.html
    title: Donate
  -
    url: /screenshots.html
    title: Screenshots
  -
    url: /privacy.html
    title: Privacy policy
  -
    url: /versionlist.html
    title: Changelog
  -
    url: /credits.html
    title: Credits
  -
    url: /sourcecode.html
    title: Sourcecode
  -
    url: /links.html
    title: Links
  -
    url: /plans.html
    title: Future plans

